# Generated by Django 5.2 on 2025-06-12 19:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias_Materia_prima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Categorias_Materia_prima',
            },
        ),
        migrations.CreateModel(
            name='Categorias_Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Categorias_Produtos',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('CPF', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Unidade_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('sigla', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'Unidade_compra',
            },
        ),
        migrations.CreateModel(
            name='Unidade_medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('sigla', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'Unidade_medida',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_materia_prima', models.CharField(max_length=100, unique=True)),
                ('metragem_por_unidade', models.CharField(default='', max_length=50)),
                ('estoque_atual', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estoque_maximo', models.IntegerField(default=100)),
                ('estoque_minimo', models.IntegerField(default=1)),
                ('custo_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('data_ultima_atualizacao', models.DateField(auto_now=True)),
                ('fornecedor_preferencial', models.CharField(max_length=100)),
                ('img_material', models.ImageField(default='', upload_to='imagens_produtos/imagens_estoque')),
                ('categoria', models.ForeignKey(db_column='categoria', on_delete=django.db.models.deletion.PROTECT, to='cadastro.categorias_materia_prima')),
                ('unidade_compra', models.ForeignKey(db_column='unidade_compra', default=None, on_delete=django.db.models.deletion.PROTECT, to='cadastro.unidade_compra')),
                ('unidade_medida', models.ForeignKey(blank=True, db_column='nome', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.unidade_medida')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField()),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('custo_producao', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('estoque_atual', models.IntegerField()),
                ('estoque_maximo', models.IntegerField(default=100)),
                ('estoque_minimo', models.IntegerField(default=1)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('img_produto', models.ImageField(blank=True, default=True, null=True, upload_to='media/imagens_produtos/imagens_estoque')),
                ('categoria', models.ForeignKey(db_column='categoria', default='Sem Categoria', on_delete=django.db.models.deletion.PROTECT, to='cadastro.categorias_produtos')),
            ],
            options={
                'db_table': 'Produto',
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('moldes', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('tamanho', models.CharField(max_length=50)),
                ('materiais', models.ForeignKey(db_column='materiais_id', on_delete=django.db.models.deletion.PROTECT, to='cadastro.materiaprima')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes', to='cadastro.produto')),
            ],
            options={
                'db_table': 'Producao',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(db_column='Valor')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(db_column='comprador_id', on_delete=django.db.models.deletion.PROTECT, related_name='vendas_por_id', to='cadastro.clientes')),
                ('comprador_nome', models.ForeignKey(db_column='comprador_nome', on_delete=django.db.models.deletion.PROTECT, related_name='vendas_por_nome', to='cadastro.clientes', to_field='nome')),
            ],
            options={
                'db_table': 'Vendas',
            },
        ),
    ]
