# Generated by Django 5.2 on 2025-05-19 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(db_column='categoria', default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastro.categorias', to_field='nome'),
            preserve_default=False,
        ),
    ]
