# Generated by Django 5.2 on 2025-05-19 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_item_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantidade_maxima',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(2)]),
        ),
    ]
