# Generated by Django 5.2 on 2025-06-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20250615_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias_materia_prima',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
